// Mocks generated by Mockito 5.4.6 from annotations
// in github_issue_manager/test/usecase/fetch_issues_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:github_issue_manager/model/issue_model.dart' as _i2;
import 'package:github_issue_manager/repository/github_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIssueModel_0 extends _i1.SmartFake implements _i2.IssueModel {
  _FakeIssueModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GitHubRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitHubRepository extends _i1.Mock implements _i3.GitHubRepository {
  MockGitHubRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.IssueModel>> fetchIssues({String? state = 'open'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchIssues,
          [],
          {#state: state},
        ),
        returnValue: _i4.Future<List<_i2.IssueModel>>.value(<_i2.IssueModel>[]),
      ) as _i4.Future<List<_i2.IssueModel>>);

  @override
  _i4.Future<_i2.IssueModel> createIssue({
    required String? title,
    String? body,
    List<String>? labels,
    String? assignee,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createIssue,
          [],
          {
            #title: title,
            #body: body,
            #labels: labels,
            #assignee: assignee,
          },
        ),
        returnValue: _i4.Future<_i2.IssueModel>.value(_FakeIssueModel_0(
          this,
          Invocation.method(
            #createIssue,
            [],
            {
              #title: title,
              #body: body,
              #labels: labels,
              #assignee: assignee,
            },
          ),
        )),
      ) as _i4.Future<_i2.IssueModel>);

  @override
  _i4.Future<_i2.IssueModel> updateIssue({
    required int? number,
    String? title,
    String? body,
    String? state,
    List<String>? labels,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIssue,
          [],
          {
            #number: number,
            #title: title,
            #body: body,
            #state: state,
            #labels: labels,
          },
        ),
        returnValue: _i4.Future<_i2.IssueModel>.value(_FakeIssueModel_0(
          this,
          Invocation.method(
            #updateIssue,
            [],
            {
              #number: number,
              #title: title,
              #body: body,
              #state: state,
              #labels: labels,
            },
          ),
        )),
      ) as _i4.Future<_i2.IssueModel>);

  @override
  _i4.Future<_i2.IssueModel> closeIssue(int? number) => (super.noSuchMethod(
        Invocation.method(
          #closeIssue,
          [number],
        ),
        returnValue: _i4.Future<_i2.IssueModel>.value(_FakeIssueModel_0(
          this,
          Invocation.method(
            #closeIssue,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.IssueModel>);

  @override
  _i4.Future<_i2.IssueModel> reopenIssue(int? number) => (super.noSuchMethod(
        Invocation.method(
          #reopenIssue,
          [number],
        ),
        returnValue: _i4.Future<_i2.IssueModel>.value(_FakeIssueModel_0(
          this,
          Invocation.method(
            #reopenIssue,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.IssueModel>);

  @override
  _i4.Future<List<_i2.IssueModel>> searchIssues(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchIssues,
          [query],
        ),
        returnValue: _i4.Future<List<_i2.IssueModel>>.value(<_i2.IssueModel>[]),
      ) as _i4.Future<List<_i2.IssueModel>>);
}
